rules:
    american_english: ~
    avoid_repetetive_words: ~
    blank_line_after_directive: ~
    blank_line_before_directive: ~
    composer_dev_option_not_at_the_end: ~
    correct_code_block_directive_based_on_the_content: ~
    deprecated_directive_should_have_version: ~
    extension_xlf_instead_of_xliff: ~
    indention: ~
    lowercase_as_in_use_statements: ~
    max_blank_lines:
        max: 2
    no_blank_line_after_filepath_in_php_code_block: ~
    no_blank_line_after_filepath_in_twig_code_block: ~
    no_blank_line_after_filepath_in_xml_code_block: ~
    no_blank_line_after_filepath_in_yaml_code_block: ~
    no_inheritdoc: ~
    no_namespace_after_use_statements: ~
    no_space_before_self_xml_closing_tag: ~
    ordered_use_statements: ~
    replace_code_block_types: ~
    replacement: ~
    short_array_syntax: ~
    typo: ~
    unused_links: ~
    use_deprecated_directive_instead_of_versionadded: ~
    use_https_xsd_urls: ~
    valid_inline_highlighted_namespaces: ~
    valid_use_statements: ~
    versionadded_directive_should_have_version: ~
    yaml_instead_of_yml_suffix: ~
    yarn_dev_option_at_the_end: ~
