name: "CI"

on:
    pull_request:
    push:
        branches:
            - 'master'

env:
    fail-fast: true

jobs:
    test:
        name: "PHP ${{ matrix.php-version }} + DEPS=${{ matrix.deps }}"

        runs-on: ubuntu-latest

        continue-on-error: ${{ matrix.allow-failures }}

        strategy:
            matrix:
                php-version:
                    - '7.1.3'
                    - '7.2'
                deps: [no]
                allow-failures: [false]
                include:
                    - php-version: '7.1.3'
                      deps: 'low'
                      allow-failures: false

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2.3.3

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@2.7.0
              with:
                  coverage: "none"
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: "Add PHPUnit matcher"
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: "Set composer cache directory"
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: "Cache composer"
              uses: actions/cache@v2.1.2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}-deps-${{ matrix.deps }}-allow-failures-${{ matrix.allow-failures }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            - if: matrix.deps == 'low'
              run: composer --prefer-lowest --prefer-stable update

            - if: matrix.deps = 'no'
              run: composer update

            - name: "Install PHPUnit"
              run: vendor/bin/simple-phpunit install

            - name: "PHPUnit version"
              run: vendor/bin/simple-phpunit --version

            - name: "Run tests"
              run: vendor/bin/simple-phpunit
